### PR TITLE
Update django version 1.11

### PR DESCRIPTION
**Pull request by lowitea**

### CODE REVIEW

**Comment by marazmiki** [comment]
Hi, @lowitea 

Thank you very much for your contribution, but the source codes inside the ``master`` branch is completely outdated and all the new code resides inside ``dev`` one. It's completely my fault, I should merge it to ``master``, but I didn't. Sorry about that. 

If you're about to use ``django-webdav-storage``, you can get a working copy from the ``dev`` branch, coz it production-ready. I'd merge it with ``master``, but still struggling with Travis-CI (local tests running via ``tox`` are passed  completely)

**Comment by lowitea** [comment]
I understood.
May need help?
Got any release plans?

**Comment by marazmiki** [comment]
Sure, any help is appreciated. 

If you really want to help and have time to do that, please, struggle with Travis-CI :) Shying to say, but it's always a headache for me - I've never configured Travis for the first try and always make a bunch of commits to achieve that.
At the same time, all the tests have been running on a local machine via tox, are 100% passed.

Regarding release plans... perhaps, as far as we get 100% tests passed in Travis, we can roll out the release on PyPI.

**Comment by lowitea** [comment]
> Regarding release plans... perhaps, as far as we get 100% tests passed in Travis, we can roll out the release on PyPI.

Good news :) I will really wait)

> If you really want to help and have time to do that, please, struggle with Travis-CI :)

Ok. I'll try) Dev will be the main branch?

**Comment by marazmiki** [comment]
> Dev will be the main branch?

Is the branch where development resides :) So yes, all the investigations about Travis should be put there.

**Pull request closed without merging**
